### ISSUE TITLE
Broken logic in consumer

### ISSUE THREAD

**Issue by quicklizard99** [EDITD/queue_util#10]
The consumer has a callable `handle_data`, typically a generator function that yields tuples `queue_name, payload`. Because it is a generator function, `handle_data` will not be executed until its client consumes generated values. However, the consumer contains marks the job as successful with statsd and calls `post_handle_data` (https://github.com/EDITD/queue_util/blob/e4e615816d945578b2115ad9be9d33c1bb31bc6d/queue_util/consumer.py#L120-L122) before the values generated by `handle_data` are consumed (https://github.com/EDITD/queue_util/blob/e4e615816d945578b2115ad9be9d33c1bb31bc6d/queue_util/consumer.py#L149).

**Comment by sujaymansingh** [comment]
Good spot!

**Comment by gchazot** [comment]
Current state of the Consumer handles generators fine.
